### ISSUE TITLE
Timestamps must be monotonically increasing (went from 333333 to 291666)

### ISSUE THREAD

**Issue by TiagoSilvaPereira** [dmnsgn/canvas-record#15]
Sometimes I have the following error when using canvas-record:

```
Error: Timestamps must be monotonically increasing (went from 333333 to 291666).
    at _D.vC (https://alpha.rapidmockup.net/js/canvas-recorder.js:4:99)
    at _D.og (https://alpha.rapidmockup.net/js/canvas-recorder.js:1:16534)
    at _D.addVideoChunkRaw (https://alpha.rapidmockup.net/js/canvas-recorder.js:1:13711)
    at _D.addVideoChunk (https://alpha.rapidmockup.net/js/canvas-recorder.js:1:13522)
    at output (https://alpha.rapidmockup.net/js/canvas-recorder.js:8:6093)
```

I'm not sure yet what may cause this error, but I'll investigate, and if I find more details, I'll send them here.

**Comment by TiagoSilvaPereira** [comment]
Seems this is related to mp4-muxer
